#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8189 #端口号
spring:
  profiles: dev # 开发环境
  application:
    name: eureka_server
    
eureka:
  instance:
    hostname: localhost 
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl:
      defaultZone: http://localhost:8188/eureka/
  server:
    enable-self-preservation: false # 禁用自我保护机制*****************
---
server:
  port: 8289 #端口号
spring:
  profiles: prod # 生产环境
  application:
    name: eureka_server

eureka:
  instance:
    hostname: localhost 
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl:
      defaultZone: http://localhost:8288/eureka/
  server:
    enable-self-preservation: true # 开启自我保护机制*****************
    
#保存时注意，选择 UTF-8 保存